require 'anderson.plugins.impatient'
require 'anderson.plugins.dashboard'
require 'anderson.plugins.fine-cmdline'
require 'anderson.plugins.telescope'
require 'anderson.plugins.treesitter'
require 'anderson.plugins.chatgpt'
